/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenges;

public class ArrayShift {
    public static int[] insertShiftArray(int[] input, int element) {
        int[] output = new int[input.length + 1];

        int middleIndex = (input.length + 1) / 2;

        output[middleIndex] = element;

        for (int i = 0; i < input.length; i++) {
            if (i < middleIndex) {
                output[i] = input[i];
            } else {
                output[i + 1] = input[i];
            }
            return output;
        }
        return output;
    }
}
