/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenges;

import org.junit.Test;
import static org.junit.Assert.*;

public class ArrayShiftTest {
    @Test public void testInsertShiftArray() {
        int[] original1 = {2,4,6,8};
        int[] original2 = {4,8,15,23,42};
        int[] expected1 = {2,4,5,6,8};
        int[] expected2 = {4,8,15,16,23,42};

        assertArrayEquals("Inserting into the array with an even number of elements",
                ArrayShift.insertShiftArray(original1,5), expected1);
        assertArrayEquals("Should insert odd number",
                ArrayShift.insertShiftArray(original2,16), expected2);
    }
}
